# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal Projects and Interests
email: ben@treegecko.com
description: > # this means to ignore newlines until "baseurl:"
  Hobbies, projects and other personal interests.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://treegecko.com"

twitter_username: brian_e_nelson
github_username:  brian-nelson

# Build settings
markdown: kramdown

theme: jekyll-theme-midnight
